# For more information: https://laravel.com/docs/sail
version: '3'
services:
    api.davorminchorov.test:
        container_name: davorminchorov_api
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-8000}:8000'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            PHP_IDE_CONFIG: serverName=Docker
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - mysql_testing
    mysql:
        container_name: davorminchorov_mysql
        image: 'mariadb:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

    mysql_testing:
      container_name: davorminchorov_mysql_testing
      image: 'mariadb:latest'
      ports:
          - '${FORWARD_DB_PORT:-3307}:3307'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_TEST_PASSWORD}'
          MYSQL_DATABASE: '${DB_TEST_DATABASE}'
          MYSQL_USER: '${DB_TEST_USERNAME}'
          MYSQL_PASSWORD: '${DB_TEST_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
          - 'sailmysqltesting:/var/lib/mysql'
      networks:
          - sail
      healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-p${DB_TEST_PASSWORD}" ]
          retries: 3
          timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailmysqltesting:
        driver: local
