name: Integrate

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        name: Build

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  extension: zip, json

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction --no-suggest

            - name: Generate new Emoji Pack
              run: php app generate
