name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
    services:
      mysql_testing:
        image: mysql:latest
        ports:
          - 3307:3307
        env:
          MYSQL_DATABASE: davorminchorov_testing
          MYSQL_HOST: localhost
          MYSQL_USER: davorminchorov_testing
          MYSQL_PASSWORD: davorminchorov_testing
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, intl
      - run: cp .env.example .env
      - run: composer install --no-interaction --ignore-platform-reqs --no-scripts
      - run: vendor/bin/phpunit --verbose
