name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FILESYSTEM_DRIVER: local
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PASSWORD: davorminchorov
      DB_USERNAME: davorminchorov
      DB_DATABASE: davorminchorov
    services:
      mysql:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_PASSWORD: davorminchorov
          MYSQL_USER: davorminchorov
          MYSQL_DB: davorminchorov
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.0
          extensions: dom, curl, mbstring, zip, pcntl, intl
      - run: php -r "file_exists('.env') || copy('.env.example', '.env')"
      - run: composer install --no-interaction --ignore-platform-reqs --no-scripts
      - run: vendor/bin/phpunit --verbose
